export const CIE10_COMMON = [
  { code: "A09", description: "Diarrhea and gastroenteritis of presumed infectious origin" },
  { code: "B34", description: "Viral infection of unspecified site" },
  { code: "E11", description: "Non-insulin-dependent diabetes mellitus" },
  { code: "E66", description: "Obesity" },
  { code: "G43", description: "Migraine" },
  { code: "G44", description: "Other headache syndromes" },
  { code: "H10", description: "Conjunctivitis" },
  { code: "H66", description: "Suppurative and unspecified otitis media" },
  { code: "I10", description: "Essential (primary) hypertension" },
  { code: "I11", description: "Hypertensive heart disease" },
  { code: "J00", description: "Acute nasopharyngitis (common cold)" },
  { code: "J01", description: "Acute sinusitis" },
  { code: "J02", description: "Acute pharyngitis" },
  { code: "J03", description: "Acute tonsillitis" },
  { code: "J04", description: "Acute laryngitis and tracheitis" },
  { code: "J06", description: "Acute upper respiratory infections of multiple or unspecified sites" },
  { code: "J11", description: "Influenza due to unidentified virus" },
  { code: "J18", description: "Pneumonia, unspecified organism" },
  { code: "J20", description: "Acute bronchitis" },
  { code: "J30", description: "Vasomotor and allergic rhinitis" },
  { code: "J40", description: "Bronchitis, not specified as acute or chronic" },
  { code: "J45", description: "Asthma" },
  { code: "K21", description: "Gastro-esophageal reflux disease" },
  { code: "K29", description: "Gastritis and duodenitis" },
  { code: "K30", description: "Dyspepsia" },
  { code: "K35", description: "Acute appendicitis" },
  { code: "K52", description: "Other non-infective gastroenteritis and colitis" },
  { code: "K59", description: "Constipation" },
  { code: "L03", description: "Cellulitis" },
  { code: "L20", description: "Atopic dermatitis" },
  { code: "L23", description: "Allergic contact dermatitis" },
  { code: "L70", description: "Acne" },
  { code: "M13", description: "Other arthritis" },
  { code: "M54", description: "Dorsalgia" },
  { code: "M62", description: "Other disorders of muscle" },
  { code: "M79", description: "Other soft tissue disorders, not elsewhere classified" },
  { code: "N30", description: "Cystitis" },
  { code: "N39", description: "Other disorders of urinary system" },
  { code: "R05", description: "Cough" },
  { code: "R06", description: "Abnormalities of breathing" },
  { code: "R07", description: "Pain in chest" },
  { code: "R10", description: "Abdominal and pelvic pain" },
  { code: "R11", description: "Nausea and vomiting" },
  { code: "R42", description: "Dizziness and giddiness" },
  { code: "R50", description: "Fever of unknown origin" },
  { code: "R51", description: "Headache" },
  { code: "R52", description: "Pain, not elsewhere classified" },
  { code: "R53", description: "Malaise and fatigue" },
  { code: "U07", description: "Emergency conditions (COVID-19)" },
  { code: "Z00", description: "General medical examination and investigation of persons without complaint or reported diagnosis" }
];
