export const MEDICATIONS_COMMON = [
  "Abacavir",
  "Acetaminophen (Paracetamol)",
  "Acetazolamide",
  "Acetylsalicylic Acid (Aspirin)",
  "Alendronic Acid",
  "Ascorbic Acid (Vitamin C)",
  "Clavulanic Acid + Amoxicillin",
  "Folic Acid",
  "Valproic Acid",
  "Acyclovir",
  "Adrenaline (Epinephrine)",
  "Albendazole",
  "Allopurinol",
  "Alprazolam",
  "Amantadine",
  "Ambroxol",
  "Amikacin",
  "Amiodarone",
  "Amitriptyline",
  "Amlodipine",
  "Amoxicillin",
  "Ampicillin",
  "Atorvastatin",
  "Atropine",
  "Azithromycin",
  "Bacitracin",
  "Beclomethasone",
  "Benzathine Penicillin",
  "Betamethasone",
  "Sodium Bicarbonate",
  "Bisacodyl",
  "Bismuth Subsalicylate",
  "Bisoprolol",
  "Bromazepam",
  "Bromhexine",
  "Budesonide",
  "Butylscopolamine (Buscopan)",
  "Captopril",
  "Carbamazepine",
  "Carvedilol",
  "Cefadroxil",
  "Cephalexin",
  "Cefazolin",
  "Cefixime",
  "Cefotaxime",
  "Ceftazidime",
  "Ceftriaxone",
  "Cefuroxime",
  "Celecoxib",
  "Cetirizine",
  "Cyanocobalamin (Vitamin B12)",
  "Cyclophosphamide",
  "Cyclosporine",
  "Ciprofloxacin",
  "Citalopram",
  "Clarithromycin",
  "Clindamycin",
  "Clobetasol",
  "Clomipramine",
  "Clonazepam",
  "Clonidine",
  "Clopidogrel",
  "Clotrimazole",
  "Cloxacillin",
  "Clozapine",
  "Codeine",
  "Colchicine",
  "Vitamin B Complex",
  "Dapagliflozin",
  "Desloratadine",
  "Dexamethasone",
  "Dextromethorphan",
  "Diazepam",
  "Diclofenac Sodium",
  "Diclofenac Potassium",
  "Dicloxacillin",
  "Digoxin",
  "Diltiazem",
  "Dimenhydrinate",
  "Dipyrone (Metamizole)",
  "Doxazosin",
  "Doxycycline",
  "Duloxetine",
  "Enalapril",
  "Enoxaparin",
  "Erythromycin",
  "Escitalopram",
  "Spironolactone",
  "Esomeprazole",
  "Estradiol",
  "Ethambutol",
  "Ethinylestradiol",
  "Phenytoin",
  "Phenobarbital",
  "Fexofenadine",
  "Finasteride",
  "Fluconazole",
  "Fluoxetine",
  "Fluticasone",
  "Furosemide",
  "Gabapentin",
  "Gentamicin",
  "Glibenclamide",
  "Gliclazide",
  "Glucose",
  "Haloperidol",
  "Hydralazine",
  "Hydrochlorothiazide",
  "Hydrocortisone",
  "Hydroxychloroquine",
  "Iron (Ferrous Sulfate)",
  "Ibuprofen",
  "Imipenem",
  "Indomethacin",
  "Human Insulin",
  "Insulin Glargine",
  "Ipratropium Bromide",
  "Irbesartan",
  "Isoniazid",
  "Isosorbide Dinitrate",
  "Itraconazole",
  "Ivermectin",
  "Ketoconazole",
  "Ketoprofen",
  "Ketorolac",
  "Lactulose",
  "Lamivudine",
  "Lamotrigine",
  "Lansoprazole",
  "Latanoprost",
  "Levofloxacin",
  "Levonorgestrel",
  "Levothyroxine",
  "Lidocaine",
  "Linagliptin",
  "Liraglutide",
  "Lisinopril",
  "Lithium Carbonate",
  "Loperamide",
  "Loratadine",
  "Lorazepam",
  "Losartan Potassium",
  "Lovastatin",
  "Magnesium Sulfate",
  "Mannitol",
  "Mebendazole",
  "Medroxyprogesterone",
  "Meloxicam",
  "Metamizole",
  "Metformin",
  "Methyldopa",
  "Methylprednisolone",
  "Metoclopramide",
  "Metoprolol",
  "Metronidazole",
  "Miconazole",
  "Midazolam",
  "Morphine",
  "Mupirocin",
  "Naproxen",
  "Neomycin",
  "Nifedipine",
  "Nystatin",
  "Nitrofurantoin",
  "Nitroglycerin",
  "Norethisterone",
  "Norfloxacin",
  "Olanzapine",
  "Olmesartan",
  "Omeprazole",
  "Ondansetron",
  "Oxycodone",
  "Pantoprazole",
  "Paracetamol (Acetaminophen)",
  "Paroxetine",
  "Penicillin G Benzathine",
  "Piperacillin + Tazobactam",
  "Piroxicam",
  "Potassium Chloride",
  "Pravastatin",
  "Prazosin",
  "Prednisone",
  "Prednisolone",
  "Pregabalin",
  "Procaine Penicillin",
  "Progesterone",
  "Promethazine",
  "Propranolol",
  "Quetiapine",
  "Ramipril",
  "Ranitidine",
  "Rifampin",
  "Risperidone",
  "Ritonavir",
  "Rosuvastatin",
  "Salbutamol (Albuterol)",
  "Salmeterol",
  "Sertraline",
  "Sildenafil",
  "Simvastatin",
  "Sitagliptin",
  "Sucralfate",
  "Silver Sulfadiazine",
  "Sulfamethoxazole + Trimethoprim",
  "Tadalafil",
  "Tamsulosin",
  "Telmisartan",
  "Terazosin",
  "Terbinafine",
  "Theophylline",
  "Thiamine (Vitamin B1)",
  "Timolol",
  "Tinidazole",
  "Tiotropium",
  "Tobramycin",
  "Tramadol",
  "Trazodone",
  "Triamcinolone",
  "Valacyclovir",
  "Sodium Valproate",
  "Valsartan",
  "Vancomycin",
  "Verapamil",
  "Vitamin A (Retinol)",
  "Vitamin D3 (Cholecalciferol)",
  "Vitamin K (Phytonadione)",
  "Warfarin",
  "Zidovudine",
  "Zinc Oxide",
  "Zolpidem",
  "Zopiclone",
];
