/**
 * Auth routes: /api/auth/login, /api/auth/logout, /api/auth/me
 */
import { Router } from "express";
import bcrypt from "bcryptjs";
import jwt from "jsonwebtoken";
import { AuthenticatedRequest, authenticateToken } from "../middleware/auth.js";
import { authLimiter } from "../middleware/security.js";
import { validateBody } from "../middleware/validate.js";
import { schemas } from "../schemas/index.js";
import { env, JWT_SECRET, mockUsers, dbAvailable, pool, clearVolatile } from "../config.js";
import { generateCsrfToken } from "../utils/crypto.js";

export const authRouter = Router();

authRouter.get("/api/auth/me", authenticateToken, (req: AuthenticatedRequest, res) => {
  res.json({ user: req.user });
});

authRouter.post("/api/auth/logout", (req, res) => {
  // Clear volatile test data generated by the populate endpoint
  clearVolatile();

  const cookieOpts = {
    httpOnly: true,
    secure: true,
    sameSite: "lax" as const,
    path: "/",
  };
  res.clearCookie("token", cookieOpts);
  res.clearCookie("csrf_token", { ...cookieOpts, httpOnly: false });
  res.clearCookie("__Host-token", cookieOpts);
  res.clearCookie("__Host-csrf_token", { ...cookieOpts, httpOnly: false });
  res.json({ success: true });
});

authRouter.post("/api/auth/login", authLimiter, validateBody(schemas.login), async (req, res) => {
  try {
    const { username, password, role } = req.body;

    let user: any = null;

    // Try DB only if healthy
    if (dbAvailable) {
      try {
        const dbRes = await pool.query("SELECT * FROM users WHERE username = $1", [username]);
        if (dbRes.rows.length > 0) {
          const u = dbRes.rows[0];
          user = {
            id: u.id,
            username: u.username,
            password: u.password,
            name: u.name,
            role: u.role,
            clinic_id: u.clinic_id,
            managed_doctor_ids:
              typeof u.managed_doctor_ids === "string" ? JSON.parse(u.managed_doctor_ids) : u.managed_doctor_ids,
          };
        }
      } catch (dbErr) {
        console.warn("[auth] DB login query failed");
      }
    }

    // Fallback to mock
    if (!user) {
      user = mockUsers.find((u) => u.username === username);
    }

    if (!user || !bcrypt.compareSync(password, user.password)) {
      return res.status(401).json({ error: "Invalid username or password" });
    }

    if (role && user.role.toUpperCase() !== role.toUpperCase()) {
      return res.status(401).json({ error: `User exists but does not have the ${role} role` });
    }

    const token = jwt.sign(
      {
        id: user.id,
        username: user.username,
        role: user.role,
        clinicId: user.clinic_id,
        name: user.name,
        managed_doctor_ids: user.managed_doctor_ids,
      },
      JWT_SECRET,
      { expiresIn: "8h" },
    );

    const isProd = env.NODE_ENV === "production";
    const csrfToken = generateCsrfToken();

    const cookieOpts = {
      httpOnly: true,
      secure: true,
      sameSite: "lax" as const,
      path: "/",
      maxAge: 8 * 60 * 60 * 1000, // 8 hours
    };

    const tokenCookieName = isProd ? "__Host-token" : "token";
    const csrfCookieName = isProd ? "__Host-csrf_token" : "csrf_token";

    res.cookie(tokenCookieName, token, cookieOpts);
    // CSRF double-submit cookie: readable by JS so it can be sent back as header.
    res.cookie(csrfCookieName, csrfToken, { ...cookieOpts, httpOnly: false });

    res.json({
      user: {
        id: user.id,
        username: user.username,
        role: user.role,
        clinicId: user.clinic_id,
        name: user.name,
        managed_doctor_ids: user.managed_doctor_ids,
      },
      csrfToken,
    });
  } catch (err: any) {
    res.status(500).json({ error: "Database connection error" });
  }
});
